### ISSUE TITLE
theme not loading?

### ISSUE THREAD

**Issue by Wytamma** [ROAM-JCU/roam-website-archived#4]
Hey @CexyNature,

I added in my git talk and slides but the theme is now broken... Can't figure out why maybe because the version is not pinned (this is the first build in a year)? also [fastpages](https://github.com/fastai/fastpages) has been deprecated not sure if that is related. They have a migration guide. Should we follow that?

**Comment by CexyNature** [comment]
I like Quarto because supports various programming languages and Jupyter, so fastpages recommended migration plan is good alternative. Quarto seems well maintained and with stable dependencies. However, because we do not have that many posts and because we seem to not be using much dynamic content, we could consider to create a web-blog with any other framework. What do you think? I will probably go with Quarto in the time being.

**Comment by Wytamma** [comment]
If the migration is easy then I think we should just stick with Quarto instead of reinventing the wheel

**Comment by Wytamma** [comment]
Yeah that sounds like a good plan! Let me know if you run into any trouble but think it's just best to start over.

**Comment by CexyNature** [comment]
This repository was renamed `roam-website-archived`, and a new website was published on [`roam-website`](https://github.com/ROAM-JCU/roam-website). 

This repo was archived on March 16th 2023.
